/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LOOMY
 */
public class categories extends javax.swing.JFrame {

    /**
     * Creates new form categories
     */
    public categories() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jmobile = new javax.swing.JButton();
        jlaptop = new javax.swing.JButton();
        jfootwear = new javax.swing.JButton();
        jsports = new javax.swing.JButton();
        jnext = new javax.swing.JButton();
        jlog_table = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabel2.setText("SHOPPING_CATEGORIES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 40));

        jmobile.setText("MOBILE");
        jmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmobileActionPerformed(evt);
            }
        });
        getContentPane().add(jmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, -1));

        jlaptop.setText("LAPTOPS");
        jlaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaptopActionPerformed(evt);
            }
        });
        getContentPane().add(jlaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 110, -1));

        jfootwear.setText("FOOTWEAR");
        jfootwear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfootwearActionPerformed(evt);
            }
        });
        getContentPane().add(jfootwear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, -1));

        jsports.setText("SPORTS");
        jsports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsportsActionPerformed(evt);
            }
        });
        getContentPane().add(jsports, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 110, -1));

        jnext.setText("NEXT");
        jnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnextActionPerformed(evt);
            }
        });
        getContentPane().add(jnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 80, -1));

        jlog_table.setText("LOG_TABLE");
        jlog_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlog_tableActionPerformed(evt);
            }
        });
        getContentPane().add(jlog_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\PHOTOS\\ooty\\IMG_7017.JPG")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmobileActionPerformed
       this.setVisible(false);
       MOBILE M = new MOBILE();
       M.setVisible(true);
    }//GEN-LAST:event_jmobileActionPerformed

    private void jlaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaptopActionPerformed
        this.setVisible(false);
        LAPTOPS L = new LAPTOPS();
        L.setVisible(true);
    }//GEN-LAST:event_jlaptopActionPerformed

    private void jfootwearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfootwearActionPerformed
        this.setVisible(false);
        FOOTWEAR F = new FOOTWEAR();
        F.setVisible(true);
    }//GEN-LAST:event_jfootwearActionPerformed

    private void jsportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsportsActionPerformed
        this.setVisible(false);
        SPORTS S = new SPORTS();
        S.setVisible(true);
    }//GEN-LAST:event_jsportsActionPerformed

    private void jnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnextActionPerformed
          this.setVisible(false);
          delivery_detals d = new delivery_detals();
          d.setVisible(true);
    }//GEN-LAST:event_jnextActionPerformed

    private void jlog_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlog_tableActionPerformed
        this.setVisible(false);
        log_table lb = new log_table();
          lb.setVisible(true);
    }//GEN-LAST:event_jlog_tableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        user_registration u = new user_registration();
        u.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jfootwear;
    private javax.swing.JButton jlaptop;
    private javax.swing.JButton jlog_table;
    private javax.swing.JButton jmobile;
    private javax.swing.JButton jnext;
    private javax.swing.JButton jsports;
    // End of variables declaration//GEN-END:variables
}
